apiVersion: v1
entries:
  ollama:
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.4.0
          links:
            - name: Ollama release v0.4.0
              url: https://github.com/ollama/ollama/releases/tag/v0.4.0
    apiVersion: v2
    appVersion: 0.4.0
    created: "2024-11-13T23:39:12.7905391+01:00"
    description: Get up and running with large language models locally.
    digest: c65b53d26f1195b33cb6713fb2e24dd98abd88f25f07b1e363cd32f913776573
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/prd-helm-ai/ollama-0.64.0.tgz
    version: 0.64.0
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.4.0
          links:
            - name: Ollama release v0.4.0
              url: https://github.com/ollama/ollama/releases/tag/v0.4.0
    apiVersion: v2
    appVersion: 0.4.0
    created: "2024-11-13T23:39:12.7984886+01:00"
    description: Get up and running with large language models locally.
    digest: c65b53d26f1195b33cb6713fb2e24dd98abd88f25f07b1e363cd32f913776573
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/prd-helm-ai/charts/ollama-0.64.0.tgz
    version: 0.64.0
  open-webui:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: 0.3.35
    created: "2024-11-13T23:39:12.7960256+01:00"
    dependencies:
    - condition: ollama.enabled
      import-values:
      - child: service
        parent: ollama.service
      name: ollama
      repository: https://otwld.github.io/ollama-helm/
      version: '>=0.24.0'
    - condition: pipelines.enabled
      import-values:
      - child: service
        parent: pipelines.service
      name: pipelines
      repository: https://helm.openwebui.com
      version: '>=0.0.1'
    - condition: tika.enabled
      name: tika
      repository: https://apache.jfrog.io/artifactory/tika
      version: '>=2.9.0'
    description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions
      \U0001F44B"
    digest: b97bdb4f65516d8f5411c825d5df8faa2083e2987c6cdc6ada168fdc6575b3e0
    home: https://www.openwebui.com/
    icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
    keywords:
    - llm
    - chat
    - web-ui
    name: open-webui
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/open-webui/pkgs/container/open-webui
    - https://github.com/otwld/ollama-helm/
    - https://hub.docker.com/r/ollama/ollama
    urls:
    - https://mbtraore.github.io/prd-helm-ai/open-webui-3.6.0.tgz
    version: 3.6.0
  pipelines:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: alpha
    created: "2024-11-13T23:39:12.7989735+01:00"
    description: 'Pipelines: UI-Agnostic OpenAI API Plugin Framework'
    digest: 0a29dcd7e0df8c9e0ef11822522804f023fdbc81105425fe5481e7d57689dc0b
    home: https://github.com/open-webui/pipelines
    icon: https://github.com/open-webui/pipelines/raw/main/header.png
    keywords:
    - llm
    - chat
    - web-ui
    name: pipelines
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/pipelines/pkgs/container/pipelines
    urls:
    - https://mbtraore.github.io/prd-helm-ai/charts/pipelines-0.0.4.tgz
    version: 0.0.4
  tika:
  - apiVersion: v2
    appVersion: 2.9.0.0
    created: "2024-11-13T23:39:12.7974286+01:00"
    description: The official Helm chart to deploy Apache Tika on Kubernetes
    digest: ca9fa418bcb83afc1b340d90563bedc71a83a6434a2c7c528ddaba284a55c427
    home: https://tika.apache.org
    icon: https://tika.apache.org/tika.png
    keywords:
    - apache
    - tika
    - apache-tika
    - tika-helm
    maintainers:
    - email: lewismc@apache.org
      name: lewismc
      url: https://github.com/lewismc
    - name: stijnbrouwers
      url: https://github.com/stijnbrouwers
    - name: philipsoutham
      url: https://github.com/philipsoutham
    - name: frascu
      url: https://github.com/frascu
    - name: euven
      url: https://github.com/euven
    name: tika
    sources:
    - https://github.com/apache/tika
    - https://github.com/apache/tika-helm
    type: application
    urls:
    - https://mbtraore.github.io/prd-helm-ai/tika-2.9.0.tgz
    version: 2.9.0
  - apiVersion: v2
    appVersion: 2.9.0.0
    created: "2024-11-13T23:39:12.8003236+01:00"
    description: The official Helm chart to deploy Apache Tika on Kubernetes
    digest: ca9fa418bcb83afc1b340d90563bedc71a83a6434a2c7c528ddaba284a55c427
    home: https://tika.apache.org
    icon: https://tika.apache.org/tika.png
    keywords:
    - apache
    - tika
    - apache-tika
    - tika-helm
    maintainers:
    - email: lewismc@apache.org
      name: lewismc
      url: https://github.com/lewismc
    - name: stijnbrouwers
      url: https://github.com/stijnbrouwers
    - name: philipsoutham
      url: https://github.com/philipsoutham
    - name: frascu
      url: https://github.com/frascu
    - name: euven
      url: https://github.com/euven
    name: tika
    sources:
    - https://github.com/apache/tika
    - https://github.com/apache/tika-helm
    type: application
    urls:
    - https://mbtraore.github.io/prd-helm-ai/charts/tika-2.9.0.tgz
    version: 2.9.0
generated: "2024-11-13T23:39:12.7892606+01:00"
